<template>
  <div class="dashboard-container">
    <el-select v-model="cur_floor_wuhaolou" placeholder="请选择楼层" style="float: right;">
      <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"/>
    </el-select>
    <div id="5_5" v-if="cur_floor_wuhaolou===5">
      <div class="prompt_5">* 五号楼五层限女生选择</div>
      <!-- Image Map Generated by http://www.image-map.net/ -->
      <img id="wrapImg_wuhaolou" src="../../assets/imgs/5_5_ready.jpg" usemap="#image-map" style="width:1000px;height:312.656px">
      <map id="WuhaolouMap" name="image-map">
        <area target="" alt="5514" title="5514" href="./room/5514" coords="17,194,100,376" shape="rect">
        <area target="" alt="5513" title="5513" href="" coords="106,191,188,380" shape="rect">
        <area target="" alt="5512" title="5512" href="" coords="191,190,268,377" shape="rect">
        <area target="" alt="5511" title="5511" href="" coords="270,191,346,380" shape="rect">
        <area target="" alt="5510" title="5510" href="" coords="351,190,430,380" shape="rect">
        <area target="" alt="5509" title="5509" href="" coords="433,189,513,377" shape="rect">
        <area target="" alt="5508" title="5508" href="" coords="517,191,599,380" shape="rect">
        <area target="" alt="5507" title="5507" href="" coords="928,191,1008,383" shape="rect">
        <area target="" alt="5506" title="5506" href="" coords="1010,190,1093,377" shape="rect">
        <area target="" alt="5505" title="5505" href="" coords="1092,189,1175,376" shape="rect">
        <area target="" alt="5504" title="5504" href="" coords="1176,190,1256,377" shape="rect">
        <area target="" alt="5503" title="5503" href="" coords="1256,187,1334,375" shape="rect">
        <area target="" alt="5502" title="5502" href="" coords="1336,187,1424,375" shape="rect">
        <area target="" alt="5501" title="5501" href="" coords="1424,187,1509,377" shape="rect">
      </map>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import { adjustPosition } from '@/utils/adjustMapCoords'

export default {
  name: 'Dashboard',
  data() {
    return {
      options: [{
        value: 1,
        label: '一层'
      }, {
        value: 2,
        label: '二层'
      }, {
        value: 3,
        label: '三层'
      }, {
        value: 4,
        label: '四层'
      }, {
        value: 5,
        label: '五层'
      }],
      cur_floor_wuhaolou: 5,
    }
  },
  computed: {
    ...mapGetters([
      'name'
    ])
  },
  mounted() {
    this.autoAdjust('wrapImg_wuhaolou', 1548, 484)
  },
  methods: {
    // 图片热区点位自适应
    autoAdjust(eleId, imageWidth, imageHeigth) {
      var map = document.getElementById('WuhaolouMap')
      var element = map.childNodes
      // console.log('element:', element)
      // var itemNumber = element.length / 2
      for (var i = 0; i < element.length; i++) {
        var item = i
        var oldCoords = element[item].coords
        var newcoords = adjustPosition(oldCoords, eleId, imageWidth, imageHeigth)
        element[item].setAttribute('coords', newcoords)
      }
    }
  }
}
</script>

<style lang="scss" scoped>
.dashboard {
  &-container {
    margin: 30px;
  }
  &-text {
    font-size: 30px;
    line-height: 46px;
  }
}
.prompt_5 {
  color: saddlebrown;
  margin-left: 10px;
}
</style>
